### ISSUE TITLE
Add dependencies to repository

### ISSUE THREAD

**Issue by onbjerg** [Deleetdk/forudsiger_dk#11]
Something like a requirements.txt we can pip from

**Comment by Deleetdk** [comment]
System applications:
Python 3.4

Python modules:
Django 1.9.1

Nothing else. I run the server with Apache (wsgi) on Ubuntu 14.04 LTS, but one can do other things.

**Comment by onbjerg** [comment]
Still, it is good practice to add it to the repository in a file for simple setup.

**Comment by Deleetdk** [comment]
Sure.
