### ISSUE TITLE
Javascript datotid-hjælpere mangler på deploy-server, men virker på dev-server

### ISSUE THREAD

**Issue by Deleetdk** [Deleetdk/forudsiger_dk#7]
Server:
![server dato](https://cloud.githubusercontent.com/assets/6759913/12564467/ae582a4c-c3af-11e5-8fd4-6396fac30edb.png)
Dev-server:
![local](https://cloud.githubusercontent.com/assets/6759913/12564469/b46731a8-c3af-11e5-9eec-2e7fa23ac11b.png)

**Comment by Deleetdk** [comment]
Lader til at være et static problem med javascript. Underligt nok virker det meste af static-koden, men jquery mangler. Kan ses hvis man bruger F12 menyen på siderne.

**Comment by Deleetdk** [comment]
Har delvist løst problemet.
http://stackoverflow.com/questions/35016508/django-static-admin-404-for-icon-clock-gif-and-icon-calender-gif

**Comment by onbjerg** [comment]
Har du inkluderet jQuery?

**Comment by onbjerg** [comment]
Her: http://stackoverflow.com/questions/5152026/django-admin-media-prefix-url-issue

**Comment by Deleetdk** [comment]
Det er uddateret. Vi bruger django 1.9.1, det spørgsmål er fra 2011. MEDIA præfikset bliver ikke brugt længere.

**Comment by onbjerg** [comment]
Stien på dine assets der mangler er ellers /media-prefix-missing/ :)

**Comment by Deleetdk** [comment]
Det ved jeg godt, hvilket er ekstra underligt når det tilsyneladende er fjernet i nyere django...

Hackløsning: flyt filerne manuelt ind i en undermappe med det navn.

**Comment by Deleetdk** [comment]
http://stackoverflow.com/questions/35016508/django-static-admin-404-for-icon-clock-gif-and-icon-calender-gif/35056474 se løsningen i kommentarerne.
